name: Test Bun # Name it however you want

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Execute on manual trigger

jobs:
  build-and-start:
    runs-on: ubuntu-latest # Linux base image
    steps:
      - uses: actions/checkout@v3 # Checkout repo
      - uses: oven-sh/setup-bun@v1 # Setup bun
        with:
            bun-version: latest # You can also use a specific version
      - run: bun install # Only needed if you have any dependenciesrun: |
      - run: npm run format
      - run: npm run format
          
        